package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,Boolean,If,
    Then,Else,While,Function,Return,
    Identifier,Integer,LeftBrace,RightBrace,LeftParen,
    RightParen,Comma,Assign,Equal,NotEqual,
    Less,LessEqual,Plus,Minus,Or,
    And,Multiply,Divide,Comment,FloatingPoint,
    Float,Character,Char,Greater,GreaterEqual,
    SingleQuote,ScientificN
}
