package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Function,Return,If,
    Then,Else,While,Do,Identifier,
    Integer,Int,FloatingPoint,Float,Character,
    Char,Boolean,ScientificN,LeftBrace,RightBrace,
    LeftParen,RightParen,SingleQuote,Comma,Comment,
    Assign,Equal,NotEqual,Less,LessEqual,
    Greater,GreaterEqual,Not,Or,And,
    Plus,Minus,Multiply,Divide
}
